/**
 * Critical i18n resources bundled inline at build time.
 *
 * `import.meta.glob` with `eager: true` causes Vite to inline all matched
 * JSON files into the JS bundle (no runtime fetch). Used as `resources`
 * in i18n.ts so first-screen text renders with 0 RTT before any backend
 * locale fetch resolves.
 *
 * Source files generated by scripts/build-critical-i18n.mjs (auto-run
 * by package.json's `prebuild` hook).
 */
import type { Resource } from "i18next";

// Vite-specific: eager glob inlines all critical.json files at build time.
const modules = import.meta.glob("../public/locales/*/critical.json", {
  eager: true,
  import: "default"
}) as Record<string, Record<string, unknown>>;

export const criticalResources: Resource = Object.fromEntries(
  Object.entries(modules).map(([path, data]) => {
    const lang = path.match(/\/locales\/([^/]+)\/critical\.json$/)?.[1];
    if (!lang) throw new Error(`unable to parse lang from ${path}`);
    return [lang, { critical: data }];
  })
);
