/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as BlankRouteImport } from './routes/_blank'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingSplatRouteImport } from './routes/landing/$splat'
import { Route as MainAuthenticatedRouteImport } from './routes/_main/_authenticated'
import { Route as MainVipClubIndexRouteImport } from './routes/_main/vip-club/index'
import { Route as MainTournamentIndexRouteImport } from './routes/_main/tournament/index'
import { Route as MainSportsIndexRouteImport } from './routes/_main/sports/index'
import { Route as MainReferralIndexRouteImport } from './routes/_main/referral/index'
import { Route as MainGamesIndexRouteImport } from './routes/_main/games/index'
import { Route as MainFinanceIndexRouteImport } from './routes/_main/finance/index'
import { Route as MainExploreIndexRouteImport } from './routes/_main/explore/index'
import { Route as MainCasinoIndexRouteImport } from './routes/_main/casino/index'
import { Route as MainBonusIndexRouteImport } from './routes/_main/bonus/index'
import { Route as BlankTestIndexRouteImport } from './routes/_blank/test/index'
import { Route as BlankForgotpasswordIndexRouteImport } from './routes/_blank/forgotpassword/index'
import { Route as BlankBootingIndexRouteImport } from './routes/_blank/booting/index'
import { Route as MainTournamentArenaRouteImport } from './routes/_main/tournament/arena'
import { Route as MainPartnershipsPartnershipIdRouteImport } from './routes/_main/partnerships/$partnershipId'
import { Route as MainGamesGameIdRouteImport } from './routes/_main/games/$gameId'
import { Route as MainAuthenticatedProfileRouteImport } from './routes/_main/_authenticated/profile'
import { Route as MainGamesPlayGameIdRouteImport } from './routes/_main/games/play.$gameId'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/_blank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSplatRoute = LandingSplatRouteImport.update({
  id: '/landing/$splat',
  path: '/landing/$splat',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAuthenticatedRoute = MainAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MainRoute,
} as any)
const MainVipClubIndexRoute = MainVipClubIndexRouteImport.update({
  id: '/vip-club/',
  path: '/vip-club/',
  getParentRoute: () => MainRoute,
} as any)
const MainTournamentIndexRoute = MainTournamentIndexRouteImport.update({
  id: '/tournament/',
  path: '/tournament/',
  getParentRoute: () => MainRoute,
} as any)
const MainSportsIndexRoute = MainSportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => MainRoute,
} as any)
const MainReferralIndexRoute = MainReferralIndexRouteImport.update({
  id: '/referral/',
  path: '/referral/',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesIndexRoute = MainGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => MainRoute,
} as any)
const MainFinanceIndexRoute = MainFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => MainRoute,
} as any)
const MainExploreIndexRoute = MainExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => MainRoute,
} as any)
const MainCasinoIndexRoute = MainCasinoIndexRouteImport.update({
  id: '/casino/',
  path: '/casino/',
  getParentRoute: () => MainRoute,
} as any)
const MainBonusIndexRoute = MainBonusIndexRouteImport.update({
  id: '/bonus/',
  path: '/bonus/',
  getParentRoute: () => MainRoute,
} as any)
const BlankTestIndexRoute = BlankTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => BlankRoute,
} as any)
const BlankForgotpasswordIndexRoute =
  BlankForgotpasswordIndexRouteImport.update({
    id: '/forgotpassword/',
    path: '/forgotpassword/',
    getParentRoute: () => BlankRoute,
  } as any)
const BlankBootingIndexRoute = BlankBootingIndexRouteImport.update({
  id: '/booting/',
  path: '/booting/',
  getParentRoute: () => BlankRoute,
} as any)
const MainTournamentArenaRoute = MainTournamentArenaRouteImport.update({
  id: '/tournament/arena',
  path: '/tournament/arena',
  getParentRoute: () => MainRoute,
} as any)
const MainPartnershipsPartnershipIdRoute =
  MainPartnershipsPartnershipIdRouteImport.update({
    id: '/partnerships/$partnershipId',
    path: '/partnerships/$partnershipId',
    getParentRoute: () => MainRoute,
  } as any)
const MainGamesGameIdRoute = MainGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => MainRoute,
} as any)
const MainAuthenticatedProfileRoute =
  MainAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainGamesPlayGameIdRoute = MainGamesPlayGameIdRouteImport.update({
  id: '/games/play/$gameId',
  path: '/games/play/$gameId',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing/$splat': typeof LandingSplatRoute
  '/profile': typeof MainAuthenticatedProfileRoute
  '/games/$gameId': typeof MainGamesGameIdRoute
  '/partnerships/$partnershipId': typeof MainPartnershipsPartnershipIdRoute
  '/tournament/arena': typeof MainTournamentArenaRoute
  '/booting': typeof BlankBootingIndexRoute
  '/forgotpassword': typeof BlankForgotpasswordIndexRoute
  '/test': typeof BlankTestIndexRoute
  '/bonus': typeof MainBonusIndexRoute
  '/casino': typeof MainCasinoIndexRoute
  '/explore': typeof MainExploreIndexRoute
  '/finance': typeof MainFinanceIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/referral': typeof MainReferralIndexRoute
  '/sports': typeof MainSportsIndexRoute
  '/tournament': typeof MainTournamentIndexRoute
  '/vip-club': typeof MainVipClubIndexRoute
  '/games/play/$gameId': typeof MainGamesPlayGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing/$splat': typeof LandingSplatRoute
  '/profile': typeof MainAuthenticatedProfileRoute
  '/games/$gameId': typeof MainGamesGameIdRoute
  '/partnerships/$partnershipId': typeof MainPartnershipsPartnershipIdRoute
  '/tournament/arena': typeof MainTournamentArenaRoute
  '/booting': typeof BlankBootingIndexRoute
  '/forgotpassword': typeof BlankForgotpasswordIndexRoute
  '/test': typeof BlankTestIndexRoute
  '/bonus': typeof MainBonusIndexRoute
  '/casino': typeof MainCasinoIndexRoute
  '/explore': typeof MainExploreIndexRoute
  '/finance': typeof MainFinanceIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/referral': typeof MainReferralIndexRoute
  '/sports': typeof MainSportsIndexRoute
  '/tournament': typeof MainTournamentIndexRoute
  '/vip-club': typeof MainVipClubIndexRoute
  '/games/play/$gameId': typeof MainGamesPlayGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_blank': typeof BlankRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/_authenticated': typeof MainAuthenticatedRouteWithChildren
  '/landing/$splat': typeof LandingSplatRoute
  '/_main/_authenticated/profile': typeof MainAuthenticatedProfileRoute
  '/_main/games/$gameId': typeof MainGamesGameIdRoute
  '/_main/partnerships/$partnershipId': typeof MainPartnershipsPartnershipIdRoute
  '/_main/tournament/arena': typeof MainTournamentArenaRoute
  '/_blank/booting/': typeof BlankBootingIndexRoute
  '/_blank/forgotpassword/': typeof BlankForgotpasswordIndexRoute
  '/_blank/test/': typeof BlankTestIndexRoute
  '/_main/bonus/': typeof MainBonusIndexRoute
  '/_main/casino/': typeof MainCasinoIndexRoute
  '/_main/explore/': typeof MainExploreIndexRoute
  '/_main/finance/': typeof MainFinanceIndexRoute
  '/_main/games/': typeof MainGamesIndexRoute
  '/_main/referral/': typeof MainReferralIndexRoute
  '/_main/sports/': typeof MainSportsIndexRoute
  '/_main/tournament/': typeof MainTournamentIndexRoute
  '/_main/vip-club/': typeof MainVipClubIndexRoute
  '/_main/games/play/$gameId': typeof MainGamesPlayGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing/$splat'
    | '/profile'
    | '/games/$gameId'
    | '/partnerships/$partnershipId'
    | '/tournament/arena'
    | '/booting'
    | '/forgotpassword'
    | '/test'
    | '/bonus'
    | '/casino'
    | '/explore'
    | '/finance'
    | '/games'
    | '/referral'
    | '/sports'
    | '/tournament'
    | '/vip-club'
    | '/games/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing/$splat'
    | '/profile'
    | '/games/$gameId'
    | '/partnerships/$partnershipId'
    | '/tournament/arena'
    | '/booting'
    | '/forgotpassword'
    | '/test'
    | '/bonus'
    | '/casino'
    | '/explore'
    | '/finance'
    | '/games'
    | '/referral'
    | '/sports'
    | '/tournament'
    | '/vip-club'
    | '/games/play/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_blank'
    | '/_main'
    | '/_main/_authenticated'
    | '/landing/$splat'
    | '/_main/_authenticated/profile'
    | '/_main/games/$gameId'
    | '/_main/partnerships/$partnershipId'
    | '/_main/tournament/arena'
    | '/_blank/booting/'
    | '/_blank/forgotpassword/'
    | '/_blank/test/'
    | '/_main/bonus/'
    | '/_main/casino/'
    | '/_main/explore/'
    | '/_main/finance/'
    | '/_main/games/'
    | '/_main/referral/'
    | '/_main/sports/'
    | '/_main/tournament/'
    | '/_main/vip-club/'
    | '/_main/games/play/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlankRoute: typeof BlankRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  LandingSplatRoute: typeof LandingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blank': {
      id: '/_blank'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/$splat': {
      id: '/landing/$splat'
      path: '/landing/$splat'
      fullPath: '/landing/$splat'
      preLoaderRoute: typeof LandingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_authenticated': {
      id: '/_main/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainAuthenticatedRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/vip-club/': {
      id: '/_main/vip-club/'
      path: '/vip-club'
      fullPath: '/vip-club'
      preLoaderRoute: typeof MainVipClubIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/tournament/': {
      id: '/_main/tournament/'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof MainTournamentIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sports/': {
      id: '/_main/sports/'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof MainSportsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/referral/': {
      id: '/_main/referral/'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof MainReferralIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/': {
      id: '/_main/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof MainGamesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/': {
      id: '/_main/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof MainFinanceIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/explore/': {
      id: '/_main/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MainExploreIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/casino/': {
      id: '/_main/casino/'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof MainCasinoIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bonus/': {
      id: '/_main/bonus/'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof MainBonusIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_blank/test/': {
      id: '/_blank/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof BlankTestIndexRouteImport
      parentRoute: typeof BlankRoute
    }
    '/_blank/forgotpassword/': {
      id: '/_blank/forgotpassword/'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof BlankForgotpasswordIndexRouteImport
      parentRoute: typeof BlankRoute
    }
    '/_blank/booting/': {
      id: '/_blank/booting/'
      path: '/booting'
      fullPath: '/booting'
      preLoaderRoute: typeof BlankBootingIndexRouteImport
      parentRoute: typeof BlankRoute
    }
    '/_main/tournament/arena': {
      id: '/_main/tournament/arena'
      path: '/tournament/arena'
      fullPath: '/tournament/arena'
      preLoaderRoute: typeof MainTournamentArenaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/partnerships/$partnershipId': {
      id: '/_main/partnerships/$partnershipId'
      path: '/partnerships/$partnershipId'
      fullPath: '/partnerships/$partnershipId'
      preLoaderRoute: typeof MainPartnershipsPartnershipIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/$gameId': {
      id: '/_main/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof MainGamesGameIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_authenticated/profile': {
      id: '/_main/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainAuthenticatedProfileRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/games/play/$gameId': {
      id: '/_main/games/play/$gameId'
      path: '/games/play/$gameId'
      fullPath: '/games/play/$gameId'
      preLoaderRoute: typeof MainGamesPlayGameIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface BlankRouteChildren {
  BlankBootingIndexRoute: typeof BlankBootingIndexRoute
  BlankForgotpasswordIndexRoute: typeof BlankForgotpasswordIndexRoute
  BlankTestIndexRoute: typeof BlankTestIndexRoute
}

const BlankRouteChildren: BlankRouteChildren = {
  BlankBootingIndexRoute: BlankBootingIndexRoute,
  BlankForgotpasswordIndexRoute: BlankForgotpasswordIndexRoute,
  BlankTestIndexRoute: BlankTestIndexRoute,
}

const BlankRouteWithChildren = BlankRoute._addFileChildren(BlankRouteChildren)

interface MainAuthenticatedRouteChildren {
  MainAuthenticatedProfileRoute: typeof MainAuthenticatedProfileRoute
}

const MainAuthenticatedRouteChildren: MainAuthenticatedRouteChildren = {
  MainAuthenticatedProfileRoute: MainAuthenticatedProfileRoute,
}

const MainAuthenticatedRouteWithChildren =
  MainAuthenticatedRoute._addFileChildren(MainAuthenticatedRouteChildren)

interface MainRouteChildren {
  MainAuthenticatedRoute: typeof MainAuthenticatedRouteWithChildren
  MainGamesGameIdRoute: typeof MainGamesGameIdRoute
  MainPartnershipsPartnershipIdRoute: typeof MainPartnershipsPartnershipIdRoute
  MainTournamentArenaRoute: typeof MainTournamentArenaRoute
  MainBonusIndexRoute: typeof MainBonusIndexRoute
  MainCasinoIndexRoute: typeof MainCasinoIndexRoute
  MainExploreIndexRoute: typeof MainExploreIndexRoute
  MainFinanceIndexRoute: typeof MainFinanceIndexRoute
  MainGamesIndexRoute: typeof MainGamesIndexRoute
  MainReferralIndexRoute: typeof MainReferralIndexRoute
  MainSportsIndexRoute: typeof MainSportsIndexRoute
  MainTournamentIndexRoute: typeof MainTournamentIndexRoute
  MainVipClubIndexRoute: typeof MainVipClubIndexRoute
  MainGamesPlayGameIdRoute: typeof MainGamesPlayGameIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAuthenticatedRoute: MainAuthenticatedRouteWithChildren,
  MainGamesGameIdRoute: MainGamesGameIdRoute,
  MainPartnershipsPartnershipIdRoute: MainPartnershipsPartnershipIdRoute,
  MainTournamentArenaRoute: MainTournamentArenaRoute,
  MainBonusIndexRoute: MainBonusIndexRoute,
  MainCasinoIndexRoute: MainCasinoIndexRoute,
  MainExploreIndexRoute: MainExploreIndexRoute,
  MainFinanceIndexRoute: MainFinanceIndexRoute,
  MainGamesIndexRoute: MainGamesIndexRoute,
  MainReferralIndexRoute: MainReferralIndexRoute,
  MainSportsIndexRoute: MainSportsIndexRoute,
  MainTournamentIndexRoute: MainTournamentIndexRoute,
  MainVipClubIndexRoute: MainVipClubIndexRoute,
  MainGamesPlayGameIdRoute: MainGamesPlayGameIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlankRoute: BlankRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  LandingSplatRoute: LandingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
